---

- name: Provision Panhandler VM
  hosts: localhost
  vars:
    ansible_ssh_user: paloalto
    ansible_ssh_pass: panhandler
    ansible_sudo_pass: panhandler
  connection: local
  become: true

  tasks:
  - name: Install Basic dependancies
    apt:
      name: "{{ item }}"
      state: present
      update_cache: true
    with_items:
      - git
      - python-pip
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - open-vm-tools
      - vim

  - name: Add Docker apt key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
      state: present
    ignore_errors: true

  - name: Add docker apt repo
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_lsb.codename}} stable"
      update_cache: yes

  - name: Install Docker apt package
    apt:
      pkg: docker-ce
      state: latest
      update_cache: yes

  - name: Install Ansible
    pip:
      name: ansible
      state: latest

  - name: Install docker-compose
    pip:
      name: docker-compose
      state: latest

  - name: Adding pan user to docker group
    user:
      name: paloalto
      groups: sudo,docker
      append: yes

  - name: Create /opt/paloaltonetworks dir
    file:
      name: /opt/paloaltonetworks
      state: directory

  - name: Create /opt/paloaltonetworks/docker dir
    file:
      name: /opt/paloaltonetworks/docker
      state: directory

  - name: Create banner
    template:
      src: templates/issue
      dest: /etc/issue

  - name: Execute Panhandler Installer Script
    shell: curl -s -k -L http://bit.ly/2xui5gM | bash

  - name: Copy Panhandler service
    copy:
      src: templates/panhandler.service
      dest: /etc/systemd/system/panhandler.service

  - name: enable Panhandler service (docker-compose)
    systemd:
      name: panhandler
      daemon_reload: yes
      enabled: yes
      state: started
      masked: no

  - name: Run apt-get autoremove
    command: apt-get -y autoremove

  - name: Remove old apt archives
    shell: rm -rf /var/cache/apt/archives/* || exit 0

  - name: Remove old apt binary cache
    shell: rm -rf /var/cache/apt/*bin || exit 0

  - name: Remove old log files
    shell: rm -rf /var/log/*log || exit 0

  - name: Remove old tmp files
    shell: rm -rf /var/tmp/* || exit 0

  - name: Sync and Done
    command: sync

